version: "3.7"

services:
  db:
    build: .docker/mysql
    container_name: desafio-node-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql
    extra_hosts:
      - host.docker.interno:172.17.0.1

  node:
    build: .docker/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s /home/entrypoint.sh
    container_name: desafio-node-app
    ports:
      - 3333:3333
    volumes:
      - ./.docker/node/entrypoint.sh:/home/entrypoint.sh
      - ./app/:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - host.docker.interno:172.17.0.1

  nginx:
    build: .docker/nginx
    container_name: desafio-node-nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    extra_hosts:
      - host.docker.interno:172.17.0.1

volumes:
  mysqldata:
    driver: local